# Set this to false to prevent the update checker from running.
# Default: true
update-checker: true

# Set this to true if you are having issues and wish to see more console output.
# Default: false
debug-mode: false

# Set this to true to enable the command logger.
# Default: false
command-logger: false
